package com.smartagri.domain.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * DTO representing an agricultural advisory message generated by the
 * rule engine or scheduled advisory job.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AdvisoryDto {

    private Long id;

    /** Affected crop identifier (nullable for global advisories). */
    private Long cropId;

    /** Human-readable name of the affected crop. */
    private String cropName;

    /** Short advisory title / headline. */
    private String title;

    /** Detailed advisory message body. */
    private String message;

    /**
     * Severity / priority level.
     * E.g. INFO, WARNING, CRITICAL.
     */
    private String severity;

    /** Category of advisory (e.g. IRRIGATION, PEST_CONTROL, FERTILISATION). */
    private String category;

    private LocalDateTime generatedAt;

    /** Whether the farmer has acknowledged/dismissed this advisory. */
    private boolean acknowledged;
}
